# Basic Site Settings
locale                   : "en-US"
title                    : "Said Moussadeq - Data Science Portfolio"
title_separator          : "-"
name                     : &name "Said Moussadeq"
description              : &description "A collection of my data science projects showcasing skills in machine learning, NLP, data visualization, and more"
url                      : https://academicpages.github.io
baseurl                  : ""
repository               : "academicpages/academicpages.github.io"

# Author Information
author:
  avatar           : "profile.png"
  name             : "Said Moussadeq"
  pronouns         : "he/him"
  bio              : "Software Engineer | Cybersecurity Specialist | Data Scientist passionate about solving real-world problems through data-driven solutions."
  location         : "Davenport, Florida"
  employer         : "Bellevue University (MS in Data Science)"
  email            : "saidmsdq05@gmail.com"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "http://orcid.org/yourorcidurl"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=said+moussadeq"

  # Repositories and social media
  github           : "saidmsdq"
  linkedin         : "linkedinusername"
  kaggle           : "kaggleusername"
  twitter          : "twitterhandle"
  bluesky          : "bsky.app"

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   : "teaser.png"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

# SEO Related
google_site_verification : "google-site-verification-code"
bing_site_verification   : "bing-site-verification-code"

# Social Sharing
social:
  type                   : "Person"
  links:
    - https://github.com/saidmsdq
    - https://linkedin.com/in/linkedinusername
    - https://twitter.com/twitterhandle

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-12345678-9"

# Markdown Processing
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publications/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Professional Information
about_me:
  title: "About Me"
  content: |
    I am passionate about software engineering, data science, and cybersecurity, thriving on solving complex challenges across these fields. My skills include:
    - Machine Learning: Predicting outcomes, detecting fraud, and using NLP for sentiment analysis.
    - Cybersecurity: Threat analysis, vulnerability detection, and building secure systems.
    - Software Engineering: Designing scalable solutions and leveraging data for intelligent decision-making.

education:
  - institution: "Bellevue University"
    degree: "MS in Data Science"
    year: "Expected Nov-2024"
  - institution: "University of Central Florida"
    degree: "BS in Software Engineering"
    year: "2020"
  - institution: "Valencia College"
    degree: "AS in Computer Programming and Analysis"
    year: "2017"

certifications:
  - "CompTIA A+"
  - "CompTIA Security+ (Pending)"
  - "Cisco CCNA (Pending)"

skills:
  programming:
    - Python
    - R
    - SQL
    - Java
  data_science:
    - Machine Learning
    - Data Visualization (Power BI, Tableau)
    - Big Data (Hadoop, Spark)
  cybersecurity:
    - Threat Analysis
    - Network Security
    - Vulnerability Detection

projects:
  - title: "IoT Network Vulnerability Prediction"
    description: "Developed models to predict vulnerabilities in IoT networks."
  - title: "Credit Card Fraud Detection"
    description: "Built a pipeline for detecting and preventing fraudulent transactions."
  - title: "Movie Recommender System"
    description: "Created a collaborative filtering model for personalized movie recommendations."
